kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-sep3-5-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: chatbot-sep3-5-dsp-job
    namespace: chatbot-sep3-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-sep3-5-dsp-job-role